"""Genre presets: tempos, chord progressions, drum/bass patterns and instrument choices."""

# 16th-note positions within a bar (0-15) for each drum element.
DRUM_PATTERNS = {
    "afrobeats": {
        "kick": [0, 6],
        "snare": [4, 12],
        "clap": [],
        "hat8": True,
        "open_hat": [14],
        "shaker": [1, 5, 9, 13],
        "cowbell": [3, 11],
        "hat_gain": 0.5,
    },
    "gospel": {
        "kick": [0, 4, 8, 12],
        "snare": [4, 12],
        "clap": [],
        "hat8": True,
        "open_hat": [14],
        "shaker": [2, 6, 10, 14],
        "cowbell": [3, 11],
        "hat_gain": 0.45,
    },
    "hiphop": {
        "kick": [0, 10],
        "snare": [4, 12],
        "clap": [],
        "hat8": True,
        "open_hat": [14],
        "shaker": [],
        "cowbell": [6],
        "hat_gain": 0.6,
    },
    "amapiano": {
        "kick": [0, 8, 12],
        "snare": [],
        "clap": [4, 12],
        "hat8": False,
        "open_hat": [14],
        "shaker": [1, 3, 5, 7, 9, 11, 13, 15],
        "cowbell": [],
        "hat_gain": 0.4,
    },
    "ballad": {
        "kick": [0],
        "snare": [4, 12],
        "clap": [],
        "hat8": True,
        "open_hat": [],
        "shaker": [],
        "cowbell": [],
        "hat_gain": 0.3,
    },
    "edm": {
        "kick": [0, 4, 8, 12],
        "snare": [],
        "clap": [4, 12],
        "hat8": True,
        "open_hat": [14],
        "shaker": [],
        "cowbell": [],
        "hat_gain": 0.6,
    },
    "dancehall": {
        "kick": [0, 7],
        "snare": [4, 12],
        "clap": [],
        "hat8": True,
        "open_hat": [12],
        "shaker": [3, 11],
        "cowbell": [2, 6],
        "hat_gain": 0.5,
    },
}

# Bass patterns: list of (8th-note position, length in 8ths).
BASS_PATTERNS = {
    "afrobeats": [(0, 3), (3, 1), (5, 2), (7, 1)],
    "gospel": [(0, 4), (4, 4)],
    "hiphop": [(0, 2), (4, 2), (6, 2)],
    "amapiano": [(0, 2), (3, 1), (5, 2), (7, 1)],
    "ballad": [(0, 8)],
    "edm": [(0, 2), (4, 2), (8, 2), (12, 2)],
    "dancehall": [(0, 3), (5, 2), (7, 1)],
}

GENRES = {
    "afrobeats": {
        "name": "Afrobeats",
        "bpm": 112,
        "scale": "major",
        "chords": [0, 5, 3, 4],
        "bass_timbre": "modern",
        "pad": True,
        "stab": True,
        "arp": False,
        "bell": True,
        "lead_timbre": "warm",
        "moods": ["energy", "happy", "dance", "party", "africa", "joy"],
        "log": True,
        "instruments": ["log drum", "shaker percussion", "rhythmic bass guitar", "warm electric piano", "melodic lead synth", "backing chants"],
        "mix": ["Sidechain the kick to keep the log drum pocket tight", "Center the bass, wide the shaker bed", "Automate a low-pass filter between verses"],
        "master": ["Punchy 0 dBFS ceiling, -14 LUFS for streaming", "Tame 2-4 kHz to keep the electric piano sweet"],
    },
    "gospel": {
        "name": "Gospel",
        "bpm": 100,
        "scale": "major",
        "chords": [0, 4, 5, 3],
        "bass_timbre": "warm",
        "pad": True,
        "stab": True,
        "arp": False,
        "bell": True,
        "lead_timbre": "warm",
        "moods": ["worship", "praise", "prayer", "church", "faith", "hope", "god"],
        "log": False,
        "instruments": ["soaring organ", "choir pads", "hand claps", "rhythmic bass", "expressive lead vocals"],
        "mix": ["Reverb heavy on the choir pads", "Catch the clap transients without pushing them", "Wide stereo on the climax"],
        "master": ["Warm, soft-clipped master", "Moderate density to let the choir breathe"],
    },
    "hiphop": {
        "name": "Hip Hop",
        "bpm": 90,
        "scale": "minor",
        "chords": [0, 3, 5, 6],
        "bass_timbre": "modern",
        "pad": False,
        "stab": True,
        "arp": True,
        "bell": False,
        "lead_timbre": "bright",
        "moods": ["rap", "street", "grind", "hustle", "trap", "city"],
        "log": False,
        "instruments": ["808 bass", "tight hi-hats", "snare rolls", "dark pads", "plucked synth melody", "reverse effects"],
        "mix": ["Duck the 808 under the kick", "Layer hi-hat rolls into the build", "Add reverse tails before section drops"],
        "master": ["Heavy low end, -8 LUFS competitive loudness", "Keep vocals clear above the 808"],
    },
    "amapiano": {
        "name": "Amapiano",
        "bpm": 106,
        "scale": "minor",
        "chords": [0, 5, 3, 4],
        "bass_timbre": "modern",
        "pad": True,
        "stab": False,
        "arp": True,
        "bell": True,
        "lead_timbre": "bright",
        "moods": ["piano", "south africa", "log drum", "vibe", "chill"],
        "log": True,
        "instruments": ["deep log bass", "atmospheric pads", "piano stabs", "percussive groove", "vocal chops", "filtered transitions"],
        "mix": ["Log drums in the 120-180 Hz range with a soft attack", "Filter the pads for the intro and bridge", "Rhythmic sidechain on the groove"],
        "master": ["Spacious, -13 LUFS", "Low end focused but controlled"],
    },
    "ballad": {
        "name": "Ballad",
        "bpm": 72,
        "scale": "major",
        "chords": [0, 4, 5, 3],
        "bass_timbre": "warm",
        "pad": True,
        "stab": False,
        "arp": True,
        "bell": True,
        "lead_timbre": "warm",
        "moods": ["love", "sad", "romantic", "slow", "emotional", "acoustic"],
        "log": False,
        "instruments": ["warm piano", "acoustic guitar", "soft strings", "gentle bass", "expressive lead vocals"],
        "mix": ["Long reverb on the piano", "Let the strings swell in the bridge", "Automate warmth as the song grows"],
        "master": ["Dynamic, untouched peaks", "-16 LUFS acoustic-friendly loudness"],
    },
    "edm": {
        "name": "EDM",
        "bpm": 126,
        "scale": "minor",
        "chords": [0, 6, 3, 5],
        "bass_timbre": "modern",
        "pad": True,
        "stab": True,
        "arp": True,
        "bell": True,
        "lead_timbre": "bright",
        "moods": ["dance", "party", "electronic", "club", "drop", "festival"],
        "log": False,
        "instruments": ["layered synths", "punchy kick", "risers", "arpeggios", "cinematic pads"],
        "mix": ["Sidechain everything to the four-on-the-floor kick", "Build risers into every drop", "Airy top-end hats for energy"],
        "master": ["Loud -7 LUFS club master", "Clean sub below 40 Hz"],
    },
    "dancehall": {
        "name": "Dancehall",
        "bpm": 100,
        "scale": "minor",
        "chords": [0, 5, 3, 4],
        "bass_timbre": "modern",
        "pad": False,
        "stab": True,
        "arp": True,
        "bell": False,
        "lead_timbre": "bright",
        "moods": ["jamaica", "riddim", "island", "reggae", "summer"],
        "log": True,
        "instruments": ["riddim bass", "island percussion", "staccato keys", "melodic lead"],
        "mix": ["Loose swing on the shaker", "Staccato keys doubled with the riddim bass", "Sunny reverb on the lead"],
        "master": ["Warm and wide, -13 LUFS", "Bounce in the 100-200 Hz region"],
    },
}

GENRE_ALIASES = {
    "afro": "afrobeats", "afrobeats": "afrobeats", "afrobeat": "afrobeats",
    "gospel": "gospel", "church": "gospel", "worship": "gospel", "praise": "gospel",
    "hip hop": "hiphop", "hiphop": "hiphop", "hip-hop": "hiphop", "rap": "hiphop", "trap": "hiphop",
    "amapiano": "amapiano", "piano": "amapiano",
    "ballad": "ballad", "love song": "ballad", "slow": "ballad", "acoustic": "ballad",
    "edm": "edm", "electronic": "edm", "dance": "edm", "club": "edm", "techno": "edm",
    "dancehall": "dancehall", "reggae": "dancehall",
}

TEMPO_WORDS = {
    "fast": 1.18, "upbeat": 1.15, "energetic": 1.12, "slow": 0.8, "relaxed": 0.85,
    "chill": 0.9, "mellow": 0.85, "hyped": 1.2, "vibey": 1.05,
}

MOOD_WORDS = {
    "happy": ["happy", "joy", "smile", "celebrate", "fun"],
    "sad": ["sad", "tears", "cry", "heartbreak", "lonely", "pain"],
    "energetic": ["energy", "pump", "fire", "hype", "wild"],
    "calm": ["calm", "peace", "quiet", "dreamy", "soft"],
    "worship": ["worship", "praise", "lord", "god", "jesus", "amen", "holy"],
    "love": ["love", "romance", "baby", "kiss", "heart"],
}


# UI catalog: icon + friendly copy per genre. Icons are plain emoji so the
# frontend needs no image assets.
GENRE_CATALOG = {
    "afrobeats": {
        "id": "afrobeats",
        "icon": "🥁",
        "name": "Afrobeats",
        "tagline": "Rhythmic Nigerian groove",
        "bpm": GENRES["afrobeats"]["bpm"],
        "moods": ["party", "vibey", "dance"],
        "palette": ["drum kit", "log drums", "keys", "bass"],
    },
    "gospel": {
        "id": "gospel",
        "icon": "🙏",
        "name": "Gospel / Worship",
        "tagline": "Lifted, reverent praise",
        "bpm": GENRES["gospel"]["bpm"],
        "moods": ["worship", "joyful", "uplifting"],
        "palette": ["pads", "piano", "drums", "bass", "choir"],
    },
    "hiphop": {
        "id": "hiphop",
        "icon": "🎤",
        "name": "Hip-Hop",
        "tagline": "Boom-bap street anthem",
        "bpm": GENRES["hiphop"]["bpm"],
        "moods": ["hype", "dark", "street"],
        "palette": ["808", "snare", "keys", "bass"],
    },
    "amapiano": {
        "id": "amapiano",
        "icon": "🎹",
        "name": "Amapiano",
        "tagline": "South-African log-drum dance",
        "bpm": GENRES["amapiano"]["bpm"],
        "moods": ["chill", "dance", "summer"],
        "palette": ["log drums", "keys", "shaker", "bass"],
    },
    "ballad": {
        "id": "ballad",
        "icon": "🎻",
        "name": "Ballad",
        "tagline": "Slow, emotional love song",
        "bpm": GENRES["ballad"]["bpm"],
        "moods": ["love", "sad", "romantic"],
        "palette": ["piano", "guitar", "strings", "bass"],
    },
    "edm": {
        "id": "edm",
        "icon": "⚡",
        "name": "EDM",
        "tagline": "Festival banger, four-on-the-floor",
        "bpm": GENRES["edm"]["bpm"],
        "moods": ["party", "energy", "festival"],
        "palette": ["synths", "kick", "arps", "pads"],
    },
    "dancehall": {
        "id": "dancehall",
        "icon": "🌴",
        "name": "Dancehall",
        "tagline": "Caribbean riddim bounce",
        "bpm": GENRES["dancehall"]["bpm"],
        "moods": ["island", "summer", "party"],
        "palette": ["riddim bass", "keys", "percussion", "lead"],
    },
}
