"""Genre presets: tempos, chord progressions, drum/bass patterns and instrument choices."""

# 16th-note positions within a bar (0-15) for each drum element.
DRUM_PATTERNS = {
    "afrobeats": {
        "kick": [0, 6],
        "snare": [4, 12],
        "clap": [],
        "hat8": True,
        "open_hat": [14],
        "shaker": [1, 5, 9, 13],
        "cowbell": [3, 11],
        "hat_gain": 0.5,
    },
    "gospel": {
        "kick": [0, 4, 8, 12],
        "snare": [4, 12],
        "clap": [],
        "hat8": True,
        "open_hat": [14],
        "shaker": [2, 6, 10, 14],
        "cowbell": [3, 11],
        "hat_gain": 0.45,
    },
    "hiphop": {
        "kick": [0, 10],
        "snare": [4, 12],
        "clap": [],
        "hat8": True,
        "open_hat": [14],
        "shaker": [],
        "cowbell": [6],
        "hat_gain": 0.6,
    },
    "amapiano": {
        "kick": [0, 8, 12],
        "snare": [],
        "clap": [4, 12],
        "hat8": False,
        "open_hat": [14],
        "shaker": [1, 3, 5, 7, 9, 11, 13, 15],
        "cowbell": [],
        "hat_gain": 0.4,
    },
    "ballad": {
        "kick": [0],
        "snare": [4, 12],
        "clap": [],
        "hat8": True,
        "open_hat": [],
        "shaker": [],
        "cowbell": [],
        "hat_gain": 0.3,
    },
    "edm": {
        "kick": [0, 4, 8, 12],
        "snare": [],
        "clap": [4, 12],
        "hat8": True,
        "open_hat": [14],
        "shaker": [],
        "cowbell": [],
        "hat_gain": 0.6,
    },
    "dancehall": {
        "kick": [0, 7],
        "snare": [4, 12],
        "clap": [],
        "hat8": True,
        "open_hat": [12],
        "shaker": [3, 11],
        "cowbell": [2, 6],
        "hat_gain": 0.5,
    },
}

# Bass patterns: list of (8th-note position, length in 8ths).
BASS_PATTERNS = {
    "afrobeats": [(0, 3), (3, 1), (5, 2), (7, 1)],
    "gospel": [(0, 4), (4, 4)],
    "hiphop": [(0, 2), (4, 2), (6, 2)],
    "amapiano": [(0, 2), (3, 1), (5, 2), (7, 1)],
    "ballad": [(0, 8)],
    "edm": [(0, 2), (4, 2), (8, 2), (12, 2)],
    "dancehall": [(0, 3), (5, 2), (7, 1)],
}

GENRES = {
    "afrobeats": {
        "name": "Afrobeats",
        "bpm": 112,
        "scale": "major",
        "chords": [0, 5, 3, 4],
        "bass_timbre": "modern",
        "pad": True,
        "stab": True,
        "arp": False,
        "bell": True,
        "lead_timbre": "warm",
        "moods": ["energy", "happy", "dance", "party", "africa", "joy"],
    },
    "gospel": {
        "name": "Gospel",
        "bpm": 100,
        "scale": "major",
        "chords": [0, 4, 5, 3],
        "bass_timbre": "warm",
        "pad": True,
        "stab": True,
        "arp": False,
        "bell": True,
        "lead_timbre": "warm",
        "moods": ["worship", "praise", "prayer", "church", "faith", "hope", "god"],
    },
    "hiphop": {
        "name": "Hip Hop",
        "bpm": 90,
        "scale": "minor",
        "chords": [0, 3, 5, 6],
        "bass_timbre": "modern",
        "pad": False,
        "stab": True,
        "arp": True,
        "bell": False,
        "lead_timbre": "bright",
        "moods": ["rap", "street", "grind", "hustle", "trap", "city"],
    },
    "amapiano": {
        "name": "Amapiano",
        "bpm": 106,
        "scale": "minor",
        "chords": [0, 5, 3, 4],
        "bass_timbre": "modern",
        "pad": True,
        "stab": False,
        "arp": True,
        "bell": True,
        "lead_timbre": "bright",
        "moods": ["piano", "south africa", "log drum", "vibe", "chill"],
    },
    "ballad": {
        "name": "Ballad",
        "bpm": 72,
        "scale": "major",
        "chords": [0, 4, 5, 3],
        "bass_timbre": "warm",
        "pad": True,
        "stab": False,
        "arp": True,
        "bell": True,
        "lead_timbre": "warm",
        "moods": ["love", "sad", "romantic", "slow", "emotional", "acoustic"],
    },
    "edm": {
        "name": "EDM",
        "bpm": 126,
        "scale": "minor",
        "chords": [0, 6, 3, 5],
        "bass_timbre": "modern",
        "pad": True,
        "stab": True,
        "arp": True,
        "bell": True,
        "lead_timbre": "bright",
        "moods": ["dance", "party", "electronic", "club", "drop", "festival"],
    },
    "dancehall": {
        "name": "Dancehall",
        "bpm": 100,
        "scale": "minor",
        "chords": [0, 5, 3, 4],
        "bass_timbre": "modern",
        "pad": False,
        "stab": True,
        "arp": True,
        "bell": False,
        "lead_timbre": "bright",
        "moods": ["jamaica", "riddim", "island", "reggae", "summer"],
    },
}

GENRE_ALIASES = {
    "afro": "afrobeats", "afrobeats": "afrobeats", "afrobeat": "afrobeats",
    "gospel": "gospel", "church": "gospel", "worship": "gospel", "praise": "gospel",
    "hip hop": "hiphop", "hiphop": "hiphop", "hip-hop": "hiphop", "rap": "hiphop", "trap": "hiphop",
    "amapiano": "amapiano", "piano": "amapiano",
    "ballad": "ballad", "love song": "ballad", "slow": "ballad", "acoustic": "ballad",
    "edm": "edm", "electronic": "edm", "dance": "edm", "club": "edm", "techno": "edm",
    "dancehall": "dancehall", "reggae": "dancehall",
}

TEMPO_WORDS = {
    "fast": 1.18, "upbeat": 1.15, "energetic": 1.12, "slow": 0.8, "relaxed": 0.85,
    "chill": 0.9, "mellow": 0.85, "hyped": 1.2, "vibey": 1.05,
}

MOOD_WORDS = {
    "happy": ["happy", "joy", "smile", "celebrate", "fun"],
    "sad": ["sad", "tears", "cry", "heartbreak", "lonely", "pain"],
    "energetic": ["energy", "pump", "fire", "hype", "wild"],
    "calm": ["calm", "peace", "quiet", "dreamy", "soft"],
    "worship": ["worship", "praise", "lord", "god", "jesus", "amen", "holy"],
    "love": ["love", "romance", "baby", "kiss", "heart"],
}
